services:
  api:
    build:
      context: .
      args:
        - runmode="$runmode"
    network_mode: "host"
  redis:
    image: redis:6.2.6
    network_mode: "host"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
