services:
  image_conversion_api:
    network_mode: "host"
    expose:
      - "8000"
    build:
      context: ../image_conversion_api/
      dockerfile: ../image_conversion_api/Dockerfile
    restart: on-failure
  api:
    build: .
    network_mode: "host"
    expose:
      - 8080
      - 8081
  redis:
    image: redis:6.2.6
    network_mode: "host"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
