services:
  api:
    build: .
    expose:
      - 8080
      - 8081
  redis:
    image: redis:6.2.6
    network_mode: "host"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
