name: fixie_server
description: Fixie - Your pal in daily progress
version: 1.0.1
homepage: https://fixie.world

environment:
  sdk: ^3.6.0

dependencies:
  # Serverpod
  serverpod: 2.3.0
  serverpod_auth_server: 2.3.0
  serverpod_cloud_storage_s3: 2.3.0
  serverpod_serialization: 2.3.0

  # Firebase
  firebase_cloud_messaging_flutter: ^1.0.6

  # Testing
  test: any

  # Monitoring
  sentry: ^8.3.0

  # Core
  collection: ^1.18.0
  dio: ^5.6.0
  intl: any

dev_dependencies:
  lints: ^5.1.1
