name: fixie_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: 3.4.4

dependencies:
  mailer: 6.1.0
  serverpod: ^2.0.2
  serverpod_auth_server: ^2.0.2
  test: any
  sentry: ^8.3.0
  collection: ^1.19.0

dev_dependencies:
  lints: ^3.0.0
